### ISSUE TITLE
docs: various errors

### ISSUE THREAD

**Issue by gauteh** [OpenDrift/trajan#92]
```
generating gallery for gallery... [ 67%] example_model_along_trajectory.py
WARNING: 
../../examples/example_model_along_trajectory.py unexpectedly failed to execute correctly:

    Traceback (most recent call last):
      File "/home/runner/work/trajan/trajan/examples/example_model_along_trajectory.py", line 35, in <module>
        times = nk.sel(time=slice('2022-05-10', '2022-05-20')).time.values
      File "/home/runner/micromamba-root/envs/trajan/lib/python3.10/site-packages/xarray/core/dataset.py", line 3125, in sel
        query_results = map_index_queries(
      File "/home/runner/micromamba-root/envs/trajan/lib/python3.10/site-packages/xarray/core/indexing.py", line 192, in map_index_queries
        results.append(index.sel(labels, **options))
      File "/home/runner/micromamba-root/envs/trajan/lib/python3.10/site-packages/xarray/core/indexes.py", line 742, in sel
        indexer = _query_slice(self.index, label, coord_name, method, tolerance)
      File "/home/runner/micromamba-root/envs/trajan/lib/python3.10/site-packages/xarray/core/indexes.py", line 497, in _query_slice
        indexer = index.slice_indexer(
      File "/home/runner/micromamba-root/envs/trajan/lib/python3.10/site-packages/pandas/core/indexes/datetimes.py", line [69](https://github.com/OpenDrift/trajan/actions/runs/9078707914/job/24946302877#step:5:70)7, in slice_indexer
        raise KeyError(
    KeyError: 'Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is not allowed.'
```

```
/home/runner/work/trajan/trajan/docs/source/autoapi/trajan/index.rst:156: ERROR: Unexpected indentation.
/home/runner/work/trajan/trajan/docs/source/autoapi/trajan/index.rst:157: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/runner/work/trajan/trajan/docs/source/autoapi/trajan/readers/omb_decoder/index.rst:458: ERROR: Unexpected indentation.
/home/runner/work/trajan/trajan/docs/source/autoapi/trajan/traj1d/index.rst:69: WARNING: Inline strong start-string without end-string.
/home/runner/work/trajan/trajan/docs/source/index.rst:64: WARNING: toctree contains reference to nonexisting document 'index'
looking for now-outdated files... none found
```

```
writing output... [ 92%] gallery/sg_execution_times
writing output... [ 96%] index
/home/runner/micromamba-root/envs/trajan/lib/python3.10/site-packages/matplotlib/animation.py:892: UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you output the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(
writing output... [100%] sg_execution_times
```

```
Extension error (autoapi.extension):
Handler <function build_finished at 0x7f51e2d467a0> for event 'build-finished' threw an exception (exception: [Errno 2] No such file or directory: '/home/runner/work/trajan/trajan/docs/source/autoapi')
make: *** [Makefile:21: html] Error 2
```

@knutfrode : The last error may be caused by the first ones.

**Comment by knutfrode** [comment]
This is due to a temporary bug in NorKyst aggregate, with non-monotonic time
